apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: super-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/user/pcg-k8s-training.git
    targetRevision: HEAD
    path: extended/advanced/troubleshooting-master/broken-app # Corrected path
  destination:
    server: https://kubernetes.default.svc
    namespace: super-app-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
