apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: super-app-gateway
  namespace: super-app-frontend
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: 8000
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
