apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: super-app-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: super-app-frontend # Correct namespace
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rb
  namespace: super-app-backend
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: super-app-backend
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
