apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connection-chaos
spec:
  project: default
  source:
    repoURL: https://github.com/<user>/pcg-k8s-training.git
    targetRevision: HEAD
    path: cextended/advanced/challenges/connection-chaos/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
