apiVersion: v1
kind: Pod
metadata:
  name: caddy-sa-pod
  namespace: mariusbu
spec:
  serviceAccountName: test-service-account
  containers:
  - name: caddy
    image: caddy:2.6.4
    ports:
    - containerPort: 80
