apiVersion: v1
kind: Pod
metadata:
  name: resource-hog
spec:
  containers:
  - name: memory-hog
    image: python:3.11-slim
    command: ["python"]
    args:
      - -c
      - |
        a = []
        while True:
            a.append(' ' * 10**6)  # Allocate 1MB per loop
    resources:
      requests:
        memory: "64Mi"
        cpu: "10m"
      limits:
        memory: "1Gi"
        cpu: "100m"
