apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ping-daemon
  namespace: mariusbu
spec:
  selector:
    matchLabels:
      app: ping-daemon
  template:
    metadata:
      labels:
        app: ping-daemon
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: "small-nodes"
      containers:
      - name: ping-daemon
        image: alpine
        command:
        - "ping"
        - "publiccloudgroup.com"