apiVersion: v1
kind: Pod
metadata:
  name: secret-consumer
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "echo $DATABASE_PASSWORD && sleep 3600"]
      env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
