apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-world-allowed
  namespace: argocd
spec:
  description: Allows deployment of the hello-world app to its own namespace.
  sourceRepos:
    - '*'
  destinations:
    - namespace: hello-world
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret