# ------------------------------------------------------------------------------
# Docs: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
# ------------------------------------------------------------------------------

global:
  domain: ""

controller:
  enabled: true
  metrics:
    enabled: true

server:
  enabled: true
  service:
    type: NodePort
    nodePort: 30080
  ingress:
    enabled: false
  extraArgs:
    - --insecure

repoServer:
  enabled: true
  metrics:
    enabled: true

dex:
  enabled: false 
  metrics:
    enabled: false

redis:
  enabled: true

applicationSet:
  enabled: true

notifications:
  enabled: false

configs:
  cm:
    create: true
    application.instanceLabelKey: argocd.argoproj.io/instance
    admin.enabled: "true"
    exec.enabled: "true"
    timeout.reconciliation: 180s
  rbac:
    create: true
    policy.default: role:readonly
    policy.csv: |
      g, admin-group, role:admin
  secret:
    createSecret: true
    argocdServerAdminPassword: ""
  repositories:
    my-app-repo:
      url: https://github.com/AlexStangier/k8s-hello-world #TODO change to proper repo
      type: git

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
