apiVersion: v1
kind: Namespace
metadata:
  name: volume-mount-mystery
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: volume-mount-mystery
data:
  storage_name: "my-app-data"
  data_path: "/app/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-storage  
  namespace: volume-mount-mystery
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: reference-riddle
  namespace: volume-mount-mystery
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: DATA_PATH
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: data_path
    volumeMounts:
    - name: data-volume
      mountPath: $(DATA_PATH)     
    - name: config-vol
      mountPath: /etc/config
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: application-data      
  - name: config-vol
    configMap:
      name: app-settings          