apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: mariusbu
spec:
  containers:
  - image: busybox
    command: [ "/bin/sh", "-ec", "while true; do wget -q -O- http://demo-service-hpa.mariusbu.svc.cluster.local:80; done"]
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      requests:
        cpu: 100m
        memory: 96Mi
      limits:
        cpu: 100m
        memory: 96Mi
  restartPolicy: Never