apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}
    spec:
      containers:
        - name: myapp
          image: busybox
          command: ["/bin/sh", "-c", "echo $(cat /etc/secret/password) && sleep 3600"]
          volumeMounts:
            - name: secret
              mountPath: /etc/secret
              readOnly: true
      volumes:
        - name: secret
          secret:
            secretName: {{ include "myapp.fullname" . }}-secret
