apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: jenkins 
        resources:
          requests:
            cpu: "250m"
          limits:
            memory: "256Mi"


